```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacnao-deployment
  labels:
    app: jacnao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jacnao
  template:
    metadata:
      labels:
        app: jacnao
    spec:
      containers:
      - name: jacnao
        image: example/jacnao:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: jacnao-service
spec:
  selector:
    app: jacnao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
```
